[package]
name = "kcp"
version = "0.1.5"
authors = ["Matrix <113445886@qq.com>"]
description = "Reliable-UDP Library for Rust"
license = "MIT"
readme = "README.md"
keywords = ["kcp", "udp", "reliable"]
homepage = "https://github.com/Matrix-Zhang/kcp"

[dependencies]
bytes = "0.4"
log = "0.3"

[dev-dependencies]
time = "0.1"
rand = "0.3"
env_logger = "0.4"
