[package]
name = "kcp"
version = "0.1.0"
authors = ["Matrix <113445886@qq.com>"]
description = "Reliable-UDP Library for Rust"
license = "MIT"
keywords = ["kcp", "udp", "reliable"]

[dependencies]
bytes = "0.4"
mio = "0.6"
